<a href="https://colab.research.google.com/github/zcqin/PRML-2025/blob/main/Basics_Python_Coding_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Basics of Python Coding - Part 1**

**Zengchang Qin (PhD)**   
Feb 02, 2024

zengchang.qin@gmail.com




1. Variable Assignment

In [ ]:
x = 1
y = 2
print(x+y)
print(x*y)
print(x/y)

3
2
0.5


2. String

In [ ]:
x = "Hello World!"
print(x)
print(x[6:12])
type(x)

Hello World!
World!


str

In [ ]:
name = "Beihang"
country = 'China'


print("%s is a great school in %s!" %(name, country))
print("Good student in %s!" %(name + " " + country))

# print(f ) is a new way to represent strings, e.g.:

newfun = "print(f)"
coding = "python"
print(f"{newfun} is a great function in {coding}.")


Beihang is a great school in China!
Good student in Beihang China!
print(f) is a great function in python.


3. List

In [ ]:
list_1 = [1, 2, 3, 'Mu', 'Tou', 'Ren']
list_1.append('!')

print(list_1[3])
list_1

Mu


[1, 2, 3, 'Mu', 'Tou', 'Ren', '!']

4. Set

In [ ]:
set_1 = set([1, 2, 2, 3, 2, 1, 1, 2, 2])
set_2 = set('banana')
print(set_1)
print(set_2)

print(set_1.union(set_2))



{1, 2, 3}
{'a', 'n', 'b'}
{1, 2, 3, 'a', 'b', 'n'}


5. Dictionary

In [ ]:
dict_1 = {'apple':3, 'oragne':4, 'pear':2}
dict_2 = {1: 'apple', 2:'oragne', 3: 'pear'}

dict_1.keys()
k = dict_2.keys()
v = dict_2.values()

print(k, v)


dict_keys([1, 2, 3]) dict_values(['apple', 'oragne', 'pear'])


6. Numpy

In [ ]:
import numpy as np
x = np.array([1, 4, 3])
y = np.array([[1, 4, 3], [9, 2, 7]])
z = np.arange(1, 2000, 1)
a = np.arange(1, 7)

#print(x)
#print(y)


s = 1
v = np.array([1, 2])
m = np.array([[1, 2],
        [3, 4]])
n = np.array([[5, 6],
        [7, 8]])
t= np.array([m, n])

print(s)
print(v)
print(m)
print(t)


print(y.T)
print(y.T @ y)
print(y @ y.T)

print(z)
print(a)

l = np.ones((5, 3))
e = np.empty(3)
print(l)
print(e)



1
[1 2]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 9]
 [4 2]
 [3 7]]
[[82 22 66]
 [22 20 26]
 [66 26 58]]
[[ 26  38]
 [ 38 134]]
[   1    2    3 ... 1997 1998 1999]
[1 2 3 4 5 6]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[4.9e-324 2.0e-323 1.5e-323]


7. Function

In [ ]:
def sum_fun(a, b, c):

    # this is the summation
    out1 = np.sin(a) + np.cos(b)
    out2 = np.sin(b) + np.cos(c)
    out = out1+out2
    print_hello()
    return out

def print_hello():
    print('Hello World!')

In [ ]:
print(sum_fun(1,3,5))


Hello World!
0.2762606817305445


8. If-Else

*Branching statement*

In [ ]:
def my_nested_branching(x,y,alpha, beta):
    # a very small decision tree by two attributes and the
    # space is divided into 4 sub-spaces marked by different leaf numbers.

    if x > alpha:
        if y < beta:
            out = "leaf 1"
        else:
            out = "leaf 2"
    else:
        if y > beta:
            out = "leaf 3"
        else:
            out = "leaf 4"
    return out

In [ ]:
print(my_nested_branching(2,4,3,3) )
print(my_nested_branching(4,4,3,3) )
print(my_nested_branching(2,2,3,3) )
print(my_nested_branching(4,2,3,3) )

leaf 3
leaf 2
leaf 4
leaf 1


9. Ternary Operators

*Most programming languages have ternary operators, which usually known as conditional expressions. It provides a way that we can use one-line code to evaluate the first expression if the condition is true, otherwise it evaluates the second expression. Python has its way to implement the ternary operator, which can be constructed as below:*

In [ ]:
is_student = True
is_male = True
is_female = False
person = 'student' if is_student else 'not student'

height = 175 if is_female else 160
height2 = 175 if is_male else 160

print(person)
print(f"student height in meter is: {height/100}")

student
student height in meter is: 1.6
